import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import { Inter } from 'next/font/google';
import { Card } from '@/components/ui/card';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-[100dvh] flex-col items-center justify-around">
          <SessionProvider>
            <Card className="flex h-[42rem] w-[23.625rem] flex-col overflow-hidden text-center">
              {children}
            </Card>
          </SessionProvider>
        </main>
      </body>
    </html>
  );
}
