import { Toaster } from '@/components/ui/toaster';
import { getUserSession } from '@/lib/session';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from './navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getUserSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen w-screen flex-col items-center justify-around">
          <NavBar userId={session ? session.user_id : null} />
          <div className="flex w-screen flex-1 justify-around overflow-hidden pt-24">
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
